  
  liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/taxi_go
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password