spring:
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:h2:mem:taxiGo_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  config:
    activate:
      on-profile: