spring:
  profiles: prod
  
  liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/proddb
    driver-class-name: org.postgresql.Driver
    username: produser
    password: prodpassword