spring:
  profiles: prod
  
  liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/taxiGo_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Abdo@2023