  
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:mysql://localhost:3306/taxiGo_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: